### ISSUE TITLE
Attempt to use

### ISSUE THREAD

**Issue by lipki** [CallMeFoxie/MewnbaseModded#1]
I will try an installation, and describe action by action.
And you can always correct afterwards.
Spoiler for now it does not work :)

1. clone
In the folder "itch/apps" to have the game files at hand.
`git clone https://github.com/CallMeFoxie/MewnbaseModded.git`

2. I run tool.sh
`cd MewnbaseModded/`
`sh ./tools.sh`
> Missing ENV GAME_VERSION
Ok, I create it.
`export GAME_VERSION="0.46.1"`

3. And I start again
`sh ./tools.sh`
> tools.sh: 98: tools.sh: pushd: not found
> Running task: 
> Unknown task!

pushd ... hmmm
I don't know why.
But we will do without it.

in  tool.sh
```
#pushd -n $(pwd) >/dev/null
oldpath=`pwd`
...
#popd >/dev/null
cd $oldpath
```
4. And I start again :)
`sh ./tools.sh`
> Running task: 
> Unknown task!
I am very happy to know it ;)

5. test of "gradle"
(I have to install java 8 for "gradle")
`gradle`
> Starting a Gradle Daemon (subsequent builds will be faster)
> Task :help
> Welcome to Gradle 5.0.
> ( ... )
> BUILD SUCCESSFUL in 12s
> 1 actionable task: 1 executed

6.test of "gradlew"
`gradlew`
> Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details
> Task :help 
> Welcome to Gradle 4.4.
> ( ... )
> BUILD SUCCESSFUL in 6s
> 1 actionable task: 1 executed

7. And now ?

**Comment by lipki** [comment]
7. test of "./gradlew build"
`./gradlew build`
> Task :compileJava FAILED
/home/kevin/.local/share/Trash/files/MewnbaseModded/src/main/java/eu/foxiemods/mewnloader/tools/ItemsLoader.java:5: error: package com.cairn4.moonbase does not exist
import com.cairn4.moonbase.ItemData;
( ... )

ok, so here we need the game files.

**Comment by CallMeFoxie** [comment]
do `./tools.sh workspace` and it should tell you all the required files (pretty much just the game jar, the rest is in the repo).
Oh and don't forget to git submodule init && git submodule update ;)

**Comment by lipki** [comment]
1. clone
In the folder "itch/apps" to have the game files at hand.
```
git clone https://github.com/CallMeFoxie/MewnbaseModded.git
git submodule init
git submodule update
```
wait ....
wait again ...

2. I run "tool.sh  workspace"
`cd MewnbaseModded/`
`sh ./tools.sh workspace`

**if :**
> Missing ENV GAME_VERSION

Create it.
`export GAME_VERSION="0.46.1"`

**if :**
> tools.sh: 98: tools.sh: pushd: not found

We will do without it.
in  tools.sh
```
#pushd -n $(pwd) >/dev/null
oldpath=`pwd`
...
#popd >/dev/null
cd $oldpath
```

**if :**
> Could not determine java version from '10.0.2'.

You will have to uninstall java, to reinstall only version 1.8....

**if :**
> ./tools.sh: ligne 28 : cd: game: Aucun fichier ou dossier de ce type

`mkdir game`

**if :**
> Missing source JAR!

copy ...itch/apps/mewnbase/desktop-1.0.jar
to ...MewnbaseModded/game/mewnbase-0.46.1.jar

3. Move the game files.
copy ...MewnbaseModded/game/decompiled-0.46.1
to ...MewnbaseModded/src/main/java/com/cairn4

**Comment by CallMeFoxie** [comment]
I wonder what bash version do you have that there is no pushd/popd? It works even on ancient mingw :P

All you should need to do is
```
git clone ... --recursive
export GAME_VERSION=0.46.1
mkdir -p game
cp ..pathtothejar.. game/mewnbase-${GAME_VERSION}.jar
./tools.sh workspace
```

in theory :)
